### PR TITLE
Sorting list of grammars. Adding grammar lookups for TypeScript and Powershell

### PR DESCRIPTION
**Pull request by Xapphire13**
### Description of the Change
Adding grammar scope lookups for TypeScript and Powershell. Also sorted the list for maintainability.

### Alternate Designs
n/a

### Benefits
Syntax highlighting of .ts and .ps1 markdown snippets

### Possible Drawbacks
n/a

### Applicable Issues
n/a

### CODE REVIEW

**Comment by Xapphire13** [comment]
Ping =]

**Comment by 50Wliu** [comment]
For the most part, I appreciate the alphabetization, but I think there's some special cases that we want to keep.  For example, it makes logical sense to me that `c++` and `cpp` should appear next to each other, as should all CSS-like languages.

**Comment by Xapphire13** [comment]
Reordered the list so that related grammars are next to each other, alphabetization is now only for each subgroup of grammar type.

**Comment by 50Wliu** [comment]
Both ideas would make good followup PRs :).

**Comment by Xapphire13** [comment]
Thanks for the review and merge =]

**Pull request merged**
