### PR TITLE
Use GitHub style when "Save as HTML"

### LINKED ISSUE #339: HTML Export: use github style not applied
When exporting a Markdown preview to HTML (Right-click in the preview panel > Save As HTML) the body tag is missing the attribute "data-use-github-style".

### PR DESCRIPTION
**Pull request by simurai**
This PR makes the saved HTML use the GitHub styles. Instead of the styles from the syntax theme. Use cases are probably very different, but I think the white background is still more useful for a generated HTML output.

This is just an "improvement" of the current situation and not a final fix. Better would be if the `data-use-github-style` gets added/removed based on what you have set in the settings. Or maybe a setting which styles it should use when doing a `Save as HTML`.

Improves #322 
Closes #339 #353

### CODE REVIEW

**Comment by simurai** [comment]
I think [this spec](https://github.com/atom/markdown-preview/blob/sm-save-as-html/spec/markdown-preview-view-spec.coffee#L182) needs to change?

**Comment by 50Wliu** [comment]
Hmm...this is tricky since I had to update that spec for language-javascript changes that haven't made it into a stable build yet, so it'll always fail until 1.3.0 is released.  Running specs locally with the latest version of language-javascript linked should help you see if there's any real errors.

**Comment by rzane** [comment]
:+1: I don't see why anyone would want to view rendered markdown in their current syntax theme at all.

**Comment by 50Wliu** [comment]
@simurai ran the specs locally and there's only one small change that needed to be applied.  PR should be good to go now (it's still going to fail though because that language-javascript change still hasn't landed).

**Comment by jogleasonjr** [comment]
@50Wliu how have you been running the test for this package? `apm test` on Atom as a whole, or local to the package?

**Comment by 50Wliu** [comment]
@simurai Re-ran the build and it's :green_heart: now!

**Comment by secureinfo42** [comment]
Thank you all
@rzane, I have the idea to use the markdown github theme to automatic convert docs for web

**Comment by simurai** [comment]
> Re-ran the build and it's :green_heart: now!

Ohh.. thanks. :+1:

**Comment by nickcmaynard** [comment]
This looks good to go...?

**Comment by simurai** [comment]
It got a merge conflict.. I should take another look.

**Comment by simurai** [comment]
Merged in master to fix the conflict, and re-ran CI, but it fails again. Not sure how to fix:

```bash
The command "curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh" exited with 1.
```

**Comment by 50Wliu** [comment]
It's the usual language-javascript-was-updated-but-markdown-preview-didn't-receive-the-changes-yet failures :angry:.  I think you can safely ignore them, as they were already fixed previously in this PR.

**Comment by simurai** [comment]
Ohh... the "language-javascript-was-updated-but-markdown-preview-didn't-receive-the-changes-yet failures".. ok, I'll merge it then, thanks.

**Comment by simurai** [comment]
@50Wliu Sorry, another question. If I publish a new version of `markdown-preview` and :arrow_up: it in core, will that cause the Atom build to fail?

**Comment by 50Wliu** [comment]
It *should* be fine as the failing specs here pass when tested with the version of language-javascript on atom/atom.  Maybe create a PR just to be safe though :smile:.

**Pull request merged**
