### PR TITLE
Add support for mermaid charts

### PR DESCRIPTION
**Pull request by deiwin**
Okay, so I wanted the MD preview to also draw flowcharts for me. So I updated both the markdown decoder (see gjtorikian/roaster#18) and this preview package to use [knsv/mermaid](https://github.com/knsv/mermaid). 

The outcome is visible in this screenshot that I also added to the readme:

 (I used [this trick](http://solutionoptimist.com/2013/12/28/awesome-github-tricks/), without actually submitting anything, to effectively upload it to GitHub. Do you know if it will persist?)

I would very much like to hear what you guys think of this. Some of the things I've added seem quite hacky, but I couldn't think of any better solutions either.

### CODE REVIEW

**Comment by deiwin** [comment]
Also, I'm not entirely sure about the CSS changes, but the flowchart backgrounds seemed too light without it and the text became hard to read.

**Comment by deiwin** [comment]
As for the build failure, I had this issue on my machine as well, but thought it was because I don't have the environment properly set up or I'm just doing something wrong. For some reason the dist folder doesn't get created in the roaster library :/

**Comment by deiwin** [comment]
This change probably has no place in the main package. Could be a separate one, though.

**Comment by stasberkov** [comment]
Was it merged into master? I also need this awesome feature! This editor already has it https://cloose.github.io/CuteMarkEd/
It will be really cool it Atom's markdown will also support it.

**Comment by deiwin** [comment]
It wasn't. Could've made a separate plugin for this, but a local version was enough for me at the time. Unfortunately I don't really use atom anymore, so I don't really feel like creating a new plugin out of this any longer.

**Comment by stasberkov** [comment]
Why it was not? Due to build failure?

**Comment by deiwin** [comment]
Not sure. The PR was simply ignored. But I guess features like this might be outside the scope of this plugin, so I would understand if the maintainers wouldn't want this included.

**Pull request closed without merging**
