### PR TITLE
Ignore YAML front-matter before processing markdown

### PR DESCRIPTION
**Pull request by joestrong**
Feature requested by fmaida: https://github.com/atom/markdown-preview/issues/361

I have made the markdown renderer ignore YAML metadata from the top of a markdown file before parsing.

I've required the `hexo-front-matter` package to do the parsing

### CODE REVIEW

**Comment by joestrong** [comment]
I've added a test for the feature, which is passing. The 2 failures come from the master branch.

**Comment by tlnagy** [comment]
Hey @joestrong, any chance you could update the specs so they pass? Several of the specs make assumptions that this PR breaks and that's why they are failing. If you don't have time, I might try and do that.

**Comment by joestrong** [comment]
@tlnagy I've finally gotten around to fixing the tests around this pull request 👍

**Comment by tlnagy** [comment]
Lets ping @50Wliu and see if he wants to merge. 👍

**Comment by aljopro** [comment]
Any status on when this might get merged?

**Comment by bugrasan** [comment]
any ETA for this feature?

**Comment by lee-dohm** [comment]
Thanks very much for the effort you put into this and I apologize for our delay in handling this PR.

Originally, when the `help-wanted` label was applied to #361, it was to add an option that would allow for the rendering of the Markdown Preview without the front matter. This PR doesn't implement that, but simply always renders without the front matter. This is not what we wanted because rendering the front matter is a behavior that we specifically added.

Since the last time we dug into this, we've reconsidered our desire to support the separate code paths needed for an option of this nature. More information about our thought process can be seen in #361.

Because of all of the above, I'm going to close this. Thanks again for the work you put into it and my apologies for things being drawn out so long on it.

**Pull request closed without merging**
