### PR TITLE
Remove scrollbar on code blocks

### LINKED ISSUE #286: Horizontal scrollbars in fenced code blocks obscure text
Atom 1.0.7
Mac OS X 10.10.4

When code blocks contain lines that are longer than the preview window a horizontal scrollbar appears. This obscures the last line of text in the code block. 

Eg:

```
[root@master ~]# mco --help
Failed to generate application list: RuntimeError: Cannot find config file '/etc/puppetlabs/mcollective/client.cfg'
```

atom markdown preview fenced code block horizontal scrollbar

### PR DESCRIPTION
**Pull request by simurai**
It's still possible to scroll, but it just doesn't show any scrollbars.

Improves #286 + #234

### CODE REVIEW

**Comment by kevinsawicki** [comment]
So in this case there we would no clickable way to scroll them? Just by using the trackpad/mouse wheel?

**Comment by simurai** [comment]
> Just by using the trackpad/mouse wheel?

Yes, right. Although you could click&drag if you don't have a trackpad/mouse wheel. A little cumbersome though. Or if you enable Soft Wrap in the settings, then the code block wraps.

Another issue with just hiding the scrollbars is that there is still vertical scrolling that wouldn't be needed. I guess it's for the now hidden scrollbars.

scrollbar

So ya, this PR would be just a partial fix. I guess `<atom-text-editor>` was meant to be used in a fixed container, so the scrollbars get added "inwards".

Some alternatives to hide the scrollbar:

1. Add some sort of "auto expand" mode to `<atom-text-editor>` that expands in height when vertical scrollbars get added. Also maybe disable Soft Wrap.
2. Replace `<atom-text-editor>` with `<pre><code>`, although then it would need its own syntax highlighting. If possible, would make sense to use the same library as github.com.

**Comment by simurai** [comment]
Ok, changed it so that the scrollbar is hidden by default, but shows on hover. It's still just a stop-gap solution, but at least you can click&drag.

scrollbar

**Comment by thomasjo** [comment]
> Ok, changed it so that the scrollbar is hidden by default, but shows on hover.

Nice job. Seems like a great compromise.

**Comment by simurai** [comment]
Ok, I'll merge this. It's not a perfect/final solution, but improves the current issue at least a bit.

**Pull request merged**
